prerelease

diff --git a/test/run-test b/test/run-test
--- a/test/run-test
+++ b/test/run-test
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/sh
 #
 #  run-test.sh
 #  MulleObjC
@@ -8,6 +8,57 @@
 #  (was run-mulle-scion-test)
 
 [ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"
+
+
+MULLE_EXECUTABLE_VERSION=1.0.0
+
+##########################################################################
+###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
+###########################################################################
+# #
+# # PRELUDE - Standard startup code for loading mulle-bashfunctions
+# #
+###
+
+#
+# Figure out MULLE_BASHFUNCTIONS_LIBEXEC_DIR on this machine if needed.
+#
+if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
+then
+   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
+   export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
+fi
+
+#
+# The booter reruns the executable either with bash or zsh, whatever the
+# system provides. On the second run --no-auto-shell will be set first.
+#
+if [ "$1" != --no-auto-shell ]
+then
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
+else
+   shift    # get rid of --no-auto-shell
+fi
+
+
+#
+# Include mulle-bashfunctions.sh         : default functions
+#         mulle-bashfunctions-none.sh    : almost no functions
+#         mulle-bashfunctions-minimal.sh : few functions for basic scripts
+#         mulle-bashfunctions-all.sh     : everything, even obscure functions
+#
+# Do this first to get aliases
+#
+MULLE_EXECUTABLE="${BASH_SOURCE[0]:-${(%):-%x}}"
+. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
+
+###
+# # Now we are in bash or zsh with mulle-bashfunctions loaded
+# #
+###########################################################################
+###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
+###########################################################################
+
 
 
 search_plist()
@@ -191,7 +242,7 @@ run_test()
          plist="none"
          if [ "$HAVE_WARNED" != "YES" ]
          then
-            echo "warning: no default.plist found" >&2
+            log_warning "warning: no default.plist found"
             HAVE_WARNED="YES"
          fi
       fi
@@ -292,23 +343,20 @@ test_binary()
 
    if [ $code -eq 127 ]
    then
-      echo "${MULLE_SCION} can not be run (missing shared library probably ($PWD, $PATH)" >&2
-      exit 1
+      fail "${MULLE_SCION} can not be run (missing shared library probably ($PWD, $PATH)"
    fi
 
    if [ $code -eq 111 ]
    then
-      echo "${MULLE_SCION} universe is broken (check tmp ?)" >&2
-      exit 1
+      fail "${MULLE_SCION} universe is broken (check tmp ?)"
    fi
 
    if [ $code -ne 253 ]
    then
-      echo "${MULLE_SCION} is wrong executable ($code)" >&2
-      exit 1
+      fail "${MULLE_SCION} is wrong executable ($code)"
    fi
 
-   echo "using ${MULLE_SCION} to test" >&2
+   log_verbose "using ${MULLE_SCION} to test" >&2
 }
 
 
@@ -361,7 +409,7 @@ main()
          ;;
 
          -*)
-            echo "unknown option \"$1\"" >&2 && exit 1
+            fail "unknown option \"$1\"" >&2
          ;;
 
          *)
@@ -376,13 +424,20 @@ main()
    TEST="$1"
 
    #
+   # get DEPENDENCY_DIR and friends
+   #
+   eval `mulle-sde tool-env` || exit 1
+
+
+   #
    # find executable
    #
    MULLE_SCION="`which mulle-scion`"
 
    if [ -z "${MULLE_SCION}" ]
    then
-      echo "mulle-scion can not be found (start test inside mulle-sde) PATH=\"${PATH}\"" >&2
+      echo "mulle-scion can not be found (Tip: start with \`mulle-sde test\`) PATH=\"${PATH}\" ($PWD)" >&2
+      ls -rl "${DEPENDENCY_DIR}/bin" >&2
       exit 1
    fi
 
@@ -394,13 +449,13 @@ main()
          Darwin)
             DYLD_FALLBACK_FRAMEWORK_PATH="${DEPENDENCY_DIR}/Frameworks"
             export DYLD_FALLBACK_FRAMEWORK_PATH
-            echo "DYLD_FALLBACK_FRAMEWORK_PATH='${DEPENDENCY_DIR}/Frameworks'" >&2
+            log_verbose "DYLD_FALLBACK_FRAMEWORK_PATH='${DEPENDENCY_DIR}/Frameworks'"
             ;;
 
          *)
             LD_LIBRARY_PATH="${DEPENDENCY_DIR}/lib:${LD_LIBRARY_PATH}"
             export LD_LIBRARY_PATH
-            echo "LD_LIBRARY_PATH='${DEPENDENCY_DIR}/lib:${LD_LIBRARY_PATH}'" >&2
+            log_verbose "LD_LIBRARY_PATH='${DEPENDENCY_DIR}/lib:${LD_LIBRARY_PATH}'"
             ;;
       esac
    fi
@@ -415,8 +470,7 @@ main()
       then
           echo "All tests ($RUNS) passed successfully"
       else
-         echo "no tests found" >&2
-         exit 1
+         fail "no tests found"
       fi
    else
        local directory
@@ -432,20 +486,20 @@ main()
 
        if [ "$file" = "$filename" ]
        then
-          echo "error: template file must have .scion extension" >& 2
+          fail "template file must have .scion extension"
           exit 1
        fi
 
        if [ ! -f "$TEST" ]
        then
-          echo "error: template file not found" >& 2
+          fail "error: template file not found"
           exit 1
        fi
 
        (
           cd "${directory}" && run_test "$filename" "${directory}"
        )
-       exit $?
+       return $?
    fi
 }
 
